dataset:
  train: "Sample"
  validation: "Sample"
  num_worker: 4
  batch_size: 16 # supposed to be an even number

Sample:
  train: "datasets/sample/train_data_list.csv"
  val: "datasets/sample/val_data_list.csv"
  root_dir: "datasets/sample"
FFHQ:
  train: "datasets/ffhq/train_data_list.csv"
  val: "datasets/ffhq/val_data_list.csv"
  root_dir: null
CelebAHQ:
  train: "datasets/celebahq/train_data_list.csv"
  val: "datasets/celebahq/val_data_list.csv"
  root_dir: null

checkpoint:
  save_dir: "checkpoint/"
  continue: 
    status: True
    name: "20210513_0" # checkpoint name, i.e. YYMMDD_epoch

log:
  save_dir: "log"
  file_name: "train"
  level: 10 # INFO=20, DEBUG=10

trainer:
  name: "FaceShifterTrainer"

FaceShifterTrainer:
  max_epochs: 10000
  d_step_per_g: 2 # number of training times of discriminator per that of generator
  optim:
    name: "Adam"
    lr: 0.0004
    betas: [0.0, 0.999]

IdtEncoder:
  name: "ArcFace"
  pretrained_model: "experiments/idt_encoder/ArcFace.pth"

AEINetLoss:
  weights:
    AttrLoss: 10
    RecLoss: 10
    IdtLoss: 5