dataset:
  train: "FFHQ"
  validation: "FFHQ"
  num_worker: 1
  batch_size: 4 # supposed to be an even number

FFHQ:
  train: "datasets/ffhq/train_data_list.dat"
  validation: "datasets/ffhq/validation_data_list.dat"
  root_dir: "datasets/sample"
CelebAHQ:
  train: "datasets/celebahq/train_data_list.dat"
  validation: "datasets/celebahq/validation_data_list.dat"
  root_dir: "datasets/sample"

checkpoint:
  save_dir: "checkpoint/"
  continue: 
    status: True
    name: "20210513_6" # checkpoint name, i.e. YYMMDD_epoch

log:
  save_dir: "log"
  file_name: "train"
  level: 10 # INFO=20, DEBUG=10

trainer:
  name: "FaceShifterTrainer"

FaceShifterTrainer:
  max_epochs: 10000
  d_step_per_g: 2 # number of training times of discriminator per that of generator
  optim:
    name: "Adam"
    lr: 0.0004
    betas: [0.0, 0.999]

IdtEncoder:
  name: "ArcFace"
  pretrained_model: "experiments/idt_encoder/ArcFace.pth"

AEINetLoss:
  weights:
    AttrLoss: 10
    RecLoss: 10
    IdtLoss: 5